export {
  captureAttributionFromUrl,
  getAnonymousId,
  getAttribution,
  getSessionId,
  initTracking,
  trackCheckoutStarted,
  trackCtaClick,
  trackEvent,
  trackFirstSearchCompleted,
  trackPageView,
  trackPurchaseCompleted,
  trackSignupCompleted,
  trackUpgradeClicked,
} from "@/lib/tracking";
