project_id = "yklmfcgbtprwhjehipte"

[functions.leads-sensitive]
verify_jwt = true

[functions.buscar-leads]
verify_jwt = true

[functions.analisar-lead-ia]
verify_jwt = true

[functions.create-pix-asaas]
verify_jwt = true

[functions.check-pix-payment]
verify_jwt = true

[functions.api-keys-manage]
verify_jwt = true

[functions.api-leads]
verify_jwt = false

[functions.send-email-campaign]
verify_jwt = true

[functions.kiwify-webhook]
verify_jwt = false

[functions.get-leads-secure]
verify_jwt = true

[functions.send-onboarding-email]
verify_jwt = false

[functions.track-email-open]
verify_jwt = false
