project_id = "yklmfcgbtprwhjehipte"

[functions.buscar-leads]
verify_jwt = true

[functions.analisar-lead-ia]
verify_jwt = true

[functions.create-checkout]
verify_jwt = true

[functions.check-subscription]
verify_jwt = true

[functions.customer-portal]
verify_jwt = true

[functions.create-pix-asaas]
verify_jwt = true

[functions.check-pix-payment]
verify_jwt = true
