begin;

-- Extend the existing exact/hashed lead lookup with the bounded public-site
-- context generated only by the internal Zanotelli personalization flow.
-- The v2 resolver remains the identity authority; v3 only appends context after
-- v2 has produced an unambiguous matched lead.
create or replace function public.internal_lookup_zanotelli_lead_context_v3(
  p_lead_reference uuid default null,
  p_phone_hash text default null,
  p_email_hash text default null,
  p_domain_hash text default null,
  p_company_hash text default null,
  p_responsible_hash text default null
)
returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_result jsonb;
  v_lead_id uuid;
  v_site_context jsonb := '{}'::jsonb;
begin
  v_result := public.internal_lookup_zanotelli_lead_context_v2(
    p_lead_reference,
    p_phone_hash,
    p_email_hash,
    p_domain_hash,
    p_company_hash,
    p_responsible_hash
  );

  if coalesce(v_result ->> 'status', '') <> 'matched' then
    return v_result;
  end if;

  begin
    v_lead_id := (v_result ->> 'lead_reference')::uuid;
  exception when others then
    return v_result;
  end;

  select case
      when jsonb_typeof(lead.custom_fields -> 'zanotelli_site_context') = 'object'
        then jsonb_strip_nulls(
          jsonb_build_object(
            'version', lead.custom_fields -> 'zanotelli_site_context' -> 'version',
            'generated_at', lead.custom_fields -> 'zanotelli_site_context' -> 'generated_at',
            'pages_checked', lead.custom_fields -> 'zanotelli_site_context' -> 'pages_checked',
            'title', nullif(left(coalesce(lead.custom_fields -> 'zanotelli_site_context' ->> 'title', ''), 300), ''),
            'description', nullif(left(coalesce(lead.custom_fields -> 'zanotelli_site_context' ->> 'description', ''), 700), ''),
            'headings', coalesce(lead.custom_fields -> 'zanotelli_site_context' -> 'headings', '[]'::jsonb),
            'facts', coalesce(lead.custom_fields -> 'zanotelli_site_context' -> 'facts', '[]'::jsonb)
          )
        )
      else '{}'::jsonb
    end
    into v_site_context
  from public.leads lead
  join public.zanotelli_context_scope_users scope
    on scope.user_id = lead.user_id
   and scope.active = true
  where lead.id = v_lead_id
  limit 1;

  if coalesce(v_site_context, '{}'::jsonb) = '{}'::jsonb then
    return v_result;
  end if;

  return v_result || jsonb_build_object('website_context', v_site_context);
end;
$$;

revoke all on function public.internal_lookup_zanotelli_lead_context_v3(uuid, text, text, text, text, text)
  from public, anon, authenticated;
grant execute on function public.internal_lookup_zanotelli_lead_context_v3(uuid, text, text, text, text, text)
  to service_role;

comment on function public.internal_lookup_zanotelli_lead_context_v3(uuid, text, text, text, text, text) is
  'Extends the v2 Zanotelli lead context resolver with bounded public website context generated by the internal personalization path. Identity matching remains delegated to v2.';

commit;
